[package]
name = "sql_mermaid_visualizer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "sqlvis"
path = "./src/main.rs"

[dependencies]
clap = { version = "3.0.14", features = ["derive"] }
